fastANI_show.sh:fastANI --ql OOOO_genome_list.txt --rl IIII_genome_list.txt -o OOOO_and_IIII_fastANI.out -t 52
NO_buffalo_and_buffalo_fastANI.sh:fastANI --ql NO_buffalo_genome_list.txt --rl buffalo_genome_list.txt -o NO_buffalo_and_buffalo_fastANI.out -t 52
NO_cattle_and_cattle_fastANI.sh:fastANI --ql NO_cattle_genome_list.txt --rl cattle_genome_list.txt -o NO_cattle_and_cattle_fastANI.out -t 52
NO_goat_and_goat_fastANI.sh:fastANI --ql NO_goat_genome_list.txt --rl goat_genome_list.txt -o NO_goat_and_goat_fastANI.out -t 52
NO_moose_and_moose_fastANI.sh:fastANI --ql NO_moose_genome_list.txt --rl moose_genome_list.txt -o NO_moose_and_moose_fastANI.out -t 52
NO_roe_deer_and_roe_deer_fastANI.sh:fastANI --ql NO_roe_deer_genome_list.txt --rl roe_deer_genome_list.txt -o NO_roe_deer_and_roe_deer_fastANI.out -t 52
NO_sheep_and_sheep_fastANI.sh:fastANI --ql NO_sheep_genome_list.txt --rl sheep_genome_list.txt -o NO_sheep_and_sheep_fastANI.out -t 52
NO_water_deer_and_water_deer_fastANI.sh:fastANI --ql NO_water_deer_genome_list.txt --rl water_deer_genome_list.txt -o NO_water_deer_and_water_deer_fastANI.out -t 52
NO_yak_and_yak_fastANI.sh:fastANI --ql NO_yak_genome_list.txt --rl yak_genome_list.txt -o NO_yak_and_yak_fastANI.out -t 52
other_and_buffalo_fastANI.sh:fastANI --ql other_genome_list.txt --rl buffalo_genome_list.txt -o other_and_buffalo_fastANI.out -t 52
other_and_cattle_fastANI.sh:fastANI --ql other_genome_list.txt --rl cattle_genome_list.txt -o other_and_cattle_fastANI.out -t 52
other_and_goat_fastANI.sh:fastANI --ql other_genome_list.txt --rl goat_genome_list.txt -o other_and_goat_fastANI.out -t 52
other_and_moose_fastANI.sh:fastANI --ql other_genome_list.txt --rl moose_genome_list.txt -o other_and_moose_fastANI.out -t 52
other_and_roe_deer_fastANI.sh:fastANI --ql other_genome_list.txt --rl roe_deer_genome_list.txt -o other_and_roe_deer_fastANI.out -t 52
other_and_sheep_fastANI.sh:fastANI --ql other_genome_list.txt --rl sheep_genome_list.txt -o other_and_sheep_fastANI.out -t 52
other_and_species_fastANI.sh:fastANI --ql other_genome_list.txt --rl species_genome_list.txt -o other_and_species_fastANI.out -t 52
other_and_strain_fastANI.sh:fastANI --ql other_genome_list.txt --rl strain_genome_list.txt -o other_and_strain_fastANI.out -t 52
other_and_water_deer_fastANI.sh:fastANI --ql other_genome_list.txt --rl water_deer_genome_list.txt -o other_and_water_deer_fastANI.out -t 52
other_and_yak_fastANI.sh:fastANI --ql other_genome_list.txt --rl yak_genome_list.txt -o other_and_yak_fastANI.out -t 52
strain_and_buffalo_fastANI.sh:fastANI --ql strain_genome_list.txt --rl buffalo_genome_list.txt -o strain_and_buffalo_fastANI.out -t 52
strain_and_cattle_fastANI.sh:fastANI --ql strain_genome_list.txt --rl cattle_genome_list.txt -o strain_and_cattle_fastANI.out -t 52
strain_and_goat_fastANI.sh:fastANI --ql strain_genome_list.txt --rl goat_genome_list.txt -o strain_and_goat_fastANI.out -t 52
strain_and_moose_fastANI.sh:fastANI --ql strain_genome_list.txt --rl moose_genome_list.txt -o strain_and_moose_fastANI.out -t 52
strain_and_roe_deer_fastANI.sh:fastANI --ql strain_genome_list.txt --rl roe_deer_genome_list.txt -o strain_and_roe_deer_fastANI.out -t 52
strain_and_sheep_fastANI.sh:fastANI --ql strain_genome_list.txt --rl sheep_genome_list.txt -o strain_and_sheep_fastANI.out -t 52
strain_and_water_deer_fastANI.sh:fastANI --ql strain_genome_list.txt --rl water_deer_genome_list.txt -o strain_and_water_deer_fastANI.out -t 52
strain_and_yak_fastANI.sh:fastANI --ql strain_genome_list.txt --rl yak_genome_list.txt -o strain_and_yak_fastANI.out -t 52
